removing bad lines so the dev-setup works on mac

diff --git a/scripts/lib b/scripts/lib
--- a/scripts/lib
+++ b/scripts/lib
@@ -1,7 +1,6 @@
 function exitError {
-
-  echo "Error: $1" >&2
-  exit 1
+    echo "Error: $1" >&2
+    exit 1
 }
 
 function compressAndPushAsset {
